name: project2
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1F

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/logo.png
    - assets/videos/nike.mp4
    - assets/nikeImage.jpg

  uses-material-design: true
